[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  version = "1.0.0"
  name = "github.com/kisielk/gotool"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"
